# Generated by Django 6.0.5 on 2026-05-21 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dental_supply', '0002_remove_customuser_shop_name_customuser_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='name',
            new_name='shop_name',
        ),
    ]
