# Generated by Django 6.0.5 on 2026-05-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_supply', '0003_rename_name_customuser_shop_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('category', models.CharField(choices=[('ENDODONTIC', 'Endodontic'), ('RESTORATIVE', 'Restorative'), ('SURGICAL', 'Surgical'), ('DIAGNOSTIC', 'Diagnostic')], db_index=True, max_length=55)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
