# Generated by Django 6.0.5 on 2026-05-22 07:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_supply', '0006_procurementorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorstocklisting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorstocklisting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
