# Generated by Django 6.0.5 on 2026-05-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_supply', '0007_vendorstocklisting_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorstocklisting',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
