# Generated by Django 6.0.5 on 2026-05-22 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dental_supply', '0008_vendorstocklisting_is_available'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendorstocklisting',
            unique_together={('distributor', 'product')},
        ),
    ]
